
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 896
SCREEN_DIMENSIONS = SCREEN_WIDTH, SCREEN_HEIGHT


FPS = 60

TILE_COLUMN_COUNT = 10
TILE_SIZE = SCREEN_WIDTH // TILE_COLUMN_COUNT
TILE_ROW_COUNT = SCREEN_HEIGHT // TILE_SIZE

ROBOT_SIZE = 100
GATE_SIZE = 150